use std::collections::HashMap;
use std::{env, fs, path::PathBuf};

const SPRITE_SOURCE: &str = "TW13081901.txt";
const TYPE_UNKNOWN: u8 = 0xFF;

fn main() {
    println!("cargo:rerun-if-changed=assets/app.ico");
    println!("cargo:rerun-if-changed=assets/encoder.ico");
    println!("cargo:rerun-if-changed={SPRITE_SOURCE}");
    println!("cargo:rerun-if-env-changed=ENCODER_ICON");

    generate_sprite_types().expect("generate sprite type catalog");

    let mut res = winres::WindowsResource::new();
    let icon = if std::env::var("ENCODER_ICON").ok().as_deref() == Some("1") {
        "assets/encoder.ico"
    } else {
        "assets/app.ico"
    };
    res.set_icon(icon);
    // Enable ComCtl32 v6 for native-windows-gui controls.
    res.set_manifest(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <dependency>
    <dependentAssembly>
      <assemblyIdentity
        type="win32"
        name="Microsoft.Windows.Common-Controls"
        version="6.0.0.0"
        processorArchitecture="x86"
        publicKeyToken="6595b64144ccf1df"
        language="*"
      />
    </dependentAssembly>
  </dependency>
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel level="requireAdministrator" uiAccess="false"/>
      </requestedPrivileges>
    </security>
  </trustInfo>
  <application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings>
      <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">false</dpiAware>
      <gdiScaling xmlns="http://schemas.microsoft.com/SMI/2017/WindowsSettings">true</gdiScaling>
    </windowsSettings>
  </application>
</assembly>"#,
    );
    res.compile().unwrap();
}

#[derive(Default)]
struct SpriteTypeRecords {
    direct_types: HashMap<u16, u8>,
    aliases: HashMap<u16, u16>,
}

fn generate_sprite_types() -> std::io::Result<()> {
    let raw = fs::read(SPRITE_SOURCE)?;
    let text = String::from_utf8_lossy(&raw);
    let records = parse_sprite_type_records(&text);
    let resolved = resolve_sprite_types(&records);
    let len = resolved
        .keys()
        .copied()
        .map(usize::from)
        .max()
        .map(|max| max + 1)
        .unwrap_or(0);
    let mut table = vec![TYPE_UNKNOWN; len];
    for (sprite, sprite_type) in resolved {
        table[usize::from(sprite)] = sprite_type;
    }

    let mut code = String::new();
    code.push_str("// @generated by build.rs; do not edit.\n");
    code.push_str(&format!(
        "pub const SPRITE_TYPES_LEN: usize = {};\n",
        table.len()
    ));
    code.push_str("pub static SPRITE_TYPES: [u8; SPRITE_TYPES_LEN] = [\n");
    for chunk in table.chunks(24) {
        code.push_str("    ");
        for value in chunk {
            code.push_str(&format!("{value}, "));
        }
        code.push('\n');
    }
    code.push_str("];\n");

    let out_path = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR set by cargo"))
        .join("sprite_types.rs");
    fs::write(out_path, code)
}

fn parse_sprite_type_records(text: &str) -> SpriteTypeRecords {
    let mut records = SpriteTypeRecords::default();
    let mut current_sprite: Option<u16> = None;

    for line in text.lines() {
        if let Some((sprite, alias)) = parse_sprite_record_header(line) {
            current_sprite = Some(sprite);
            if let Some(alias) = alias {
                records.aliases.insert(sprite, alias);
            }
        }

        if let (Some(sprite), Some(sprite_type)) = (current_sprite, parse_sprite_type(line)) {
            records.direct_types.insert(sprite, sprite_type);
        }
    }

    records
}

fn parse_sprite_record_header(line: &str) -> Option<(u16, Option<u16>)> {
    let line = line.trim_start().strip_prefix('#')?;
    let sprite_end = line
        .bytes()
        .position(|b| !b.is_ascii_digit())
        .unwrap_or(line.len());
    if sprite_end == 0 {
        return None;
    }

    let sprite = line[..sprite_end].parse().ok()?;
    let rest = line[sprite_end..].trim_start();
    if rest.is_empty() {
        return Some((sprite, None));
    }

    let token_end = rest
        .bytes()
        .position(|b| b.is_ascii_whitespace())
        .unwrap_or(rest.len());
    let alias = rest[..token_end]
        .split_once('=')
        .and_then(|(_, value)| value.parse::<u16>().ok());

    Some((sprite, alias))
}

fn parse_sprite_type(line: &str) -> Option<u8> {
    let tail = line.split_once("102.type(")?.1;
    let end = tail.find(')')?;
    tail[..end].trim().parse().ok()
}

fn resolve_sprite_types(records: &SpriteTypeRecords) -> HashMap<u16, u8> {
    let mut resolved = HashMap::new();
    for &sprite in records.direct_types.keys().chain(records.aliases.keys()) {
        if let Some(sprite_type) =
            resolve_sprite_type(sprite, &records.direct_types, &records.aliases)
        {
            resolved.insert(sprite, sprite_type);
        }
    }
    resolved
}

fn resolve_sprite_type(
    sprite: u16,
    direct_types: &HashMap<u16, u8>,
    aliases: &HashMap<u16, u16>,
) -> Option<u8> {
    let mut current = sprite;
    for _ in 0..16 {
        if let Some(sprite_type) = direct_types.get(&current) {
            return Some(*sprite_type);
        }
        current = *aliases.get(&current)?;
    }
    None
}
